### ISSUE TITLE
Icons are not showing on some resolutions

### ISSUE THREAD

**Issue by elemorelli** [gemorelli/CriticalRoll#19]
Device: Samsung Galaxy Ace 4
Screen: 480 x 800 pixels, 4.0 in

![photo56718436624082962](https://cloud.githubusercontent.com/assets/1661552/10909967/3dc9264e-821b-11e5-8e7a-8768bfe70a18.jpg)

**Comment by zeozone** [comment]
I think the problem is only with that resolution, kindly fix!
We need to play d&d this weekend!

**Comment by elemorelli** [comment]
Fixed on latest release, replacing FontFace with SVG icons

**Comment by Neferis** [comment]
SVG icons ftw!
