### ISSUE TITLE
Clicking on the language Select triggers the event twice

### ISSUE THREAD

**Issue by elemorelli** [gemorelli/CriticalRoll#3]
It's a known issue for the Ionic Team. I've tried some hacks, but it doesn't work.

https://github.com/driftyco/ionic/issues/2150

I think that it won't be fixed until Ionic provide full support to Windows Phone or a new IE (MS Edge) is released.

**Comment by elemorelli** [comment]
There are no <select> on the App, so the bug is invalid now.

**Comment by Neferis** [comment]
Yesss! D&D!
